server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:proxy.rlwy.net:43716/railway
    username: root
    password: sDEyonitowPRyfCOQBtkltAmhMZRaepm
    driver-class-name: yamanote.proxy.rlwy.net

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true